.\" Process this file with
.\" groff -man -Tascii doc.1
.\"
.TH Simple-Typescript-Starter "July 2020" Linux "User Manuals"
.SH NAME
Simple-Typescript-Starter
.SH SYNOPSIS
.B sts help
.B sts generate [
.I project-name
.B ] [
.I author
.B ]
.SH DESCRIPTION
.B Simple-Typescript-Starter
Package for generating a typescript scaffold with a bunch of reporters configured.  
.BR
This generates a customized Typescript 3.9 project which includes the following features:
.RS
.IP "Webpack bunding"
.IP "Webpack bundle analyzer"
.IP "Unit test with Mocha/Chai/Sinon"
.IP "Coverage report with nyc"
.IP "TSLint Html Report"
.IP "Code Duplicity Html Report (with git integration)"
.IP "Documentation with Typedoc"
.RE
.SH OPTIONS
.IP project-name
Name for the project created. Cannot contain spaces and must be lower case
.IP author
Name of the author of the project. Cannot contain spaces
.SH DIAGNOSTICS
NA
.SH BUGS
NA
.SH AUTHOR
Spitfire <twisterintwist@gmail.com>
.SH "SEE ALSO"
NA